routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/tasks');
Route::put('/tasks/{task}/update-status', [TaskController::class, 'updateStatusOnBoard']);

Route::resource('tasks', TaskController::class);
Route::get('/tasks/{task}/subtask/create', [TaskController::class, 'createSubtask'])->name('tasks.createSubtask');
Route::post('/tasks/{task}/subtask', [TaskController::class, 'storeSubtask'])->name('tasks.storeSubtask');
Route::get('/tasks/{task}/subtask/{subtask}/edit', [TaskController::class, 'editSubtask'])->name('tasks.editSubtask');
Route::put('/tasks/{task}/subtask/{subtask}', [TaskController::class, 'updateSubtask'])->name('tasks.updateSubtask');
Route::delete('/tasks/{task}/subtask/{subtask}', [TaskController::class, 'destroySubtask'])->name('tasks.destroySubtask');
Route::get('/tasks/{taskId}/subtasks/{subtaskId}', [TaskController::class, 'showSubtask'])->name('subtasks.show');

app/Models/Subtask.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Subtask extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'description', 'task_id', 'status'];

    public function task()
    {
        return $this->belongsTo(Task::class);
    }
}

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'description', 'date', 'status'];

    public function subtasks()
    {
        return $this->hasMany(Subtask::class);
    }
}

app/Models/TelegramModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Telegram\Bot\Laravel\Facades\Telegram;

class TelegramModel extends Model
{
    public function sendMessage($chatId, $text)
    {
        try {
            Telegram::sendMessage([
                'chat_id' => $chatId,
                'text' => $text,
            ]);
            
            return true;
        } catch (\Exception $e) {
            \Log::error('Telegram message sending failed: ' . $e->getMessage());

            return false;
        }
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SubtaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SubtaskController extends Controller
{
    //
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Task;
use App\Models\Subtask;
use App\Models\TelegramModel;
use Illuminate\Support\Facades\Config;

class TaskController extends Controller
{
    public function index(Request $request)
    {
        $tasks = Task::query();

        if ($request->filled('title')) {
            $tasks->where('title', 'like', '%' . $request->input('title') . '%');
        }

        if ($request->filled('status')) {
            $tasks->where('status', $request->input('status'));
        }

        $filteredTasks = $tasks->get();

        return view('tasks.index', ['tasks' => $filteredTasks]);
    }

    public function create()
    {
        return view('tasks.create');
    }

    public function store(Request $request, TelegramModel $telegram)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'date' => 'required|date',
            'status' => 'required|in:pending,in_progress,completed',
        ]);

        // Создание новой задачи в базе данных
        $newTask = Task::create([
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'date' => $request->input('date'),
            'status' => $request->input('status'),
        ]);

        $chatId = env('TELEGRAM_CHANNEL_ID');
        $text = 'Новая задача создана: ' . $newTask->title;
        $telegram->sendMessage($chatId, $text);

        return redirect()->action([TaskController::class, 'index']);
    }

    public function edit(Task $task)
    {
    }

    public function update(Request $request, Task $task)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'date' => 'required|date',
            'status' => 'required|in:pending,in_progress,completed',
        ]);

        $task->update([
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'date' => $request->input('date'),
            'status' => $request->input('status'),
        ]);

        return redirect('/tasks');
    }

    public function updateStatusOnBoard(Request $request, Task $task)
    {
        $request->validate([
            'status' => 'required|in:pending,in_progress,completed',
        ]);

        $task->update([
            'status' => $request->input('status'),
        ]);

        return redirect('/tasks');
    }

    public function destroy(Task $task)
    {
        $task->delete();

        return redirect('/tasks');
    }

    public function show(Task $task)
    {
        return view('tasks.show', ['task' => $task]);
    }

    public function createSubtask(Task $task)
    {
        return view('subtasks.create', ['task' => $task]);
    }

    public function editSubtask(Task $task, Subtask $subtask)
    {
        return view('subtasks.edit', ['task' => $task, 'subtask' => $subtask]);
    }

    public function updateSubtask(Request $request, Task $task, Subtask $subtask)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'status' => 'required|in:pending,in_progress,completed',
        ]);

        $subtask->update([
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'status' => $request->input('status'),
        ]);

        return redirect('/tasks/'.$task->id.'/subtasks/'.$subtask->id);
    }

    public function storeSubtask(Request $request, Task $task, TelegramModel $telegram)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
            'status' => 'required|in:pending,in_progress,completed',
        ]);

        $newSubtask = $task->subtasks()->create([
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'status' => $request->input('status'),
        ]);

        $chatId = env('TELEGRAM_CHANNEL_ID');
        $text = 'Новая подзадача к задаче <' . $task->title .  '> создана: ' . $newSubtask->title;
        $telegram->sendMessage($chatId, $text);

        return redirect('/tasks/'.$task->id);
    }

    public function destroySubtask(Task $task, Subtask $subtask)
    {
        $subtask->delete();

        return redirect('/tasks/'.$task->id);
    }

    public function showSubtask($taskId, $subtaskId)
    {
        $subtask = Subtask::findOrFail($subtaskId);

        return view('subtasks.show', compact('subtask'));
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Board</title>
    
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.14.0/Sortable.min.js"></script>
</head>
<body>
    <div id="app">
        @yield('content')
    </div>
</body>
</html>

resources/views/subtasks/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="text-center mt-4 mb-4">Создать новую подзадачу для задачи "{{ $task->title }}"</h1>

        <form action="{{ route('tasks.storeSubtask', $task->id) }}" method="post">
            @csrf

            <div class="form-group">
                <label for="title">Заголовок</label>
                <input type="text" class="form-control" id="title" name="title" required>
            </div>

            <div class="form-group">
                <label for="description">Описание</label>
                <textarea class="form-control" id="description" name="description" rows="3"></textarea>
            </div>

            <div class="form-group">
                <label for="status">Статус</label>
                <select class="form-control" id="status" name="status" required>
                    <option value="pending">В ожидании</option>
                    <option value="in_progress">В процессе</option>
                    <option value="completed">Завершено</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Создать подзадачу</button>
        </form>

        <a href="{{ route('tasks.show', $task->id) }}" class="btn btn-secondary mt-3">Назад к задаче</a>
    </div>
@endsection

resources/views/subtasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="mt-4 mb-4">Редактирование подзадачи</h1>
        <form action="{{ route('tasks.updateSubtask', [$task->id, $subtask->id]) }}" method="post">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="title">Заголовок:</label>
                <input type="text" class="form-control" name="title" id="title" value="{{ $subtask->title }}" required>
            </div>
            <div class="form-group">
                <label for="description">Описание:</label>
                <textarea class="form-control" name="description" id="description">{{ $subtask->description }}</textarea>
            </div>
            <div class="form-group">
                <label for="status">Статус:</label>
                <select class="form-control" name="status" id="status" required>
                    <option value="pending" {{ $subtask->status === 'pending' ? 'selected' : '' }}>В ожидании</option>
                    <option value="in_progress" {{ $subtask->status === 'in_progress' ? 'selected' : '' }}>В процессе</option>
                    <option value="completed" {{ $subtask->status === 'completed' ? 'selected' : '' }}>Завершено</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Обновить подзадачу</button>
        </form>
        <a href="{{ route('tasks.show', $task->id) }}" class="btn btn-secondary mt-2">Назад к задаче</a>
    </div>
@endsection

resources/views/subtasks/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Список подзадач для задачи: {{ $task->title }}</h1>
    <ul>
        @forelse($task->subtasks as $subtask)
            <li>
                {{ $subtask->title }} - {{ $subtask->status }}
                <a href="{{ route('tasks.editSubtask', ['task' => $task->id, 'subtask' => $subtask->id]) }}">Редактировать подзадачу</a>
            </li>
        @empty
            <li>Нет подзадач</li>
        @endforelse
    </ul>
    <a href="{{ route('tasks.show', $task->id) }}">Назад к задаче</a>
@endsection

resources/views/subtasks/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="text-center mt-4 mb-4">{{ $subtask->title }}</h1>
        <div class="card">
            <div class="card-body">
                <p class="card-text">{{ $subtask->description }}</p>
                <p class="card-text"><strong>Status:</strong> {{ $subtask->status }}</p>
                <p class="card-text"><strong>Date:</strong> {{ $subtask->created_at->format('d.m.Y H:i') }}</p>

                <a href="{{ route('tasks.editSubtask', ['task' => $subtask->task_id, 'subtask' => $subtask->id]) }}" class="btn btn-warning">Редактировать подзадачу</a>
            </div>
        </div>
    </div>
@endsection

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="text-center mt-4 mb-4">Создать новую задачу</h1>

        <form method="post" action="{{ route('tasks.store') }}">
            @csrf

            <div class="form-group">
                <label for="title">Заголовок</label>
                <input type="text" class="form-control" id="title" name="title" required>
            </div>

            <div class="form-group">
                <label for="description">Описание</label>
                <textarea class="form-control" id="description" name="description" rows="3"></textarea>
            </div>

            <div class="form-group">
                <label for="date">Дата</label>
                <input type="date" class="form-control" id="date" name="date" required>
            </div>

            <div class="form-group">
                <label for="status">Статус</label>
                <select class="form-control" id="status" name="status" required>
                    <option value="pending">Ожидающая</option>
                    <option value="in_progress">В процессе</option>
                    <option value="completed">Завершенная</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Создать задачу</button>
        </form>
    </div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="mt-4 mb-4">Редактирование задачи</h1>
        <form action="{{ route('tasks.update', $task->id) }}" method="post">
            @csrf
            @method('put')
            <div class="form-group">
                <label for="title">Заголовок:</label>
                <input type="text" class="form-control" name="title" id="title" value="{{ $task->title }}" required>
            </div>
            <div class="form-group">
                <label for="description">Описание:</label>
                <textarea class="form-control" name="description" id="description">{{ $task->description }}</textarea>
            </div>
            <div class="form-group">
                <label for="date">Дата:</label>
                <input type="date" class="form-control" name="date" id="date" value="{{ $task->date }}" required>
            </div>
            <div class="form-group">
                <label for="status">Статус:</label>
                <select class="form-control" name="status" id="status" required>
                    <option value="pending" {{ $task->status === 'pending' ? 'selected' : '' }}>В ожидании</option>
                    <option value="in_progress" {{ $task->status === 'in_progress' ? 'selected' : '' }}>В процессе</option>
                    <option value="completed" {{ $task->status === 'completed' ? 'selected' : '' }}>Завершено</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Обновить задачу</button>
        </form>
        <a href="{{ route('tasks.index') }}" class="btn btn-secondary mt-2">Назад к списку задач</a>
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <form action="{{ route('tasks.index') }}" method="get" class="mb-4">
            <div class="row align-items-end">
                <div class="col-md-6">
                    <label for="title" class="form-label">Заголовок:</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="title" name="title" value="{{ request('title') }}">
                        <button type="submit" class="btn btn-primary">Искать</button>
                    </div>
                </div>

                <div class="col-md-6">
                    <label for="status" class="form-label">Статус:</label>
                    <select class="form-select" id="status" name="status">
                        <option value="" selected>Все статусы</option>
                        <option value="pending" {{ request('status') === 'pending' ? 'selected' : '' }}>В ожидании</option>
                        <option value="in_progress" {{ request('status') === 'in_progress' ? 'selected' : '' }}>В процессе</option>
                        <option value="completed" {{ request('status') === 'completed' ? 'selected' : '' }}>Завершено</option>
                    </select>
                </div>
            </div>
        </form>
        <div class="row">
            @foreach(['pending', 'in_progress', 'completed'] as $status)
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header bg-secondary text-white">
                            <h2 class="text-center">{{ ucfirst($status) }}</h2>
                        </div>
                        <div class="card-body">
                            <ul class="list-group task-list" data-status="{{ $status }}">
                                @forelse($tasks->where('status', $status) as $task)
                                    <li class="list-group-item task-item" data-id="{{ $task->id }}">
                                        <h4>{{ $task->title }}</h4>
                                        <p><strong>Дата:</strong> {{ $task->date }}</p>
                                        <p><strong>Описание:</strong> {{ $task->description ?? 'Нет описания' }}</p>
                                        <h5>Подзадачи:</h5>
                                        @forelse($task->subtasks as $subtask)
                                            <p>{{ $subtask->title }} - {{ $subtask->status }}</p>
                                        @empty
                                            <p>Нет подзадач</p>
                                        @endforelse

                                        <div class="float-right">
                                            <a href="{{ route('tasks.createSubtask', $task->id) }}" class="btn btn-sm btn-primary" title="Создать подзадачу">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                            <a href="{{ route('tasks.edit', $task->id) }}" class="btn btn-sm btn-warning" title="Редактировать">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <form method="post" action="{{ route('tasks.destroy', $task->id) }}" class="d-inline">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-sm btn-danger" title="Удалить">
                                                    <i class="fas fa-trash-alt"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </li>
                                @empty
                                    <li class="list-group-item text-muted">Нет задач</li>
                                @endforelse
                            </ul>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

        <div class="text-center mt-4">
            <a href="{{ route('tasks.create') }}" class="btn btn-success" title="Создать новую задачу">
                <i class="fas fa-plus"></i> Создать новую задачу
            </a>
        </div>
    </div>

    <script>
        // Инициализация Sortable.js для каждого списка
        document.addEventListener('DOMContentLoaded', function () {
            var lists = document.querySelectorAll('.task-list');
            lists.forEach(function (list) {
                new Sortable(list, {
                    group: 'tasks',
                    animation: 150,
                    onEnd: function (evt) {
                        var taskId = evt.item.dataset.id;
                        var newStatus = evt.to.dataset.status;

                        // Отправляем запрос на обновление статуса в базе данных
                        fetch(`/tasks/${taskId}/update-status`, {
                            method: 'PUT',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
                            },
                            body: JSON.stringify({
                                status: newStatus
                            })
                        });
                    }
                });
            });
        });
    </script>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="text-center mt-4 mb-4">{{ $task->title }}</h1>
        <div class="card">
            <div class="card-body">
                <p class="card-text">{{ $task->description }}</p>
                <p class="card-text"><strong>Status:</strong> {{ $task->status }}</p>
                <p class="card-text"><strong>Date:</strong> {{ $task->date }}</p>

                <a href="{{ route('tasks.edit', $task->id) }}" class="btn btn-warning">Редактировать задачу</a>
            </div>
        </div>

        <h2 class="mt-4">Подзадачи</h2>
        @forelse($task->subtasks as $subtask)
            <div class="card mt-2">
                <div class="card-body">
                    <p class="card-text">{{ $subtask->title }} - {{ $subtask->status }}</p>
                </div>
            </div>
        @empty
            <p class="mt-2">Подзадач нет</p>
        @endforelse
    </div>
@endsection